---
# Idempotence test tasks

- block:
    - block:
        - name: run idempotence test
          include_role:
            name: amtega.idempotence_tester
          vars:
            idempotence_tester_inventory: "{{ docker_sandbox_inventory }}"
            idempotence_tester_group: "{{ docker_sandbox_group }}"

        - name: setup fact to store idempotence test result
          set_fact:
            docker_sandbox_idempotence_result: >-
              {{ idempotence_tester_test_result }}
      when:
        - docker_sandbox_state in ["started", "recreated"]
        - docker_sandbox_idempotence_test
        - docker_sandbox_inventory | length > 0

    - name: recreate docker containers after running idempotence test
      include_role:
        name: amtega.docker_provisioner
      vars:
        docker_provisioner_images: []
        docker_provisioner_containers: "{{ docker_sandbox_containers }}"
        docker_provisioner_container_labels:
          docker_sandbox_ppid: >-
            {{ docker_sandbox_get_ppid_result.stdout }}
          docker_sandbox_user: "{{ ansible_user_id }}"
          docker_sandbox_playbook: "{{ docker_sandbox_playbook }}"
          docker_sandbox_inventory: "{{ docker_sandbox_inventory }}"
        docker_provisioner_container_groups: ["{{ docker_sandbox_group }}"]
        docker_provisioner_container_tty: false
        docker_provisioner_inventory: "{{ docker_sandbox_inventory }}"
        docker_provisioner_container_state: started
        docker_provisioner_container_restart: true
        docker_provisioner_container_recreate: true
        docker_provisioner_force_kill: true
      when:
        - docker_sandbox_state in ["started", "recreated"]
        - docker_sandbox_idempotence_test
        - docker_sandbox_inventory | length > 0
        - docker_sandbox_idempotence_test_recreate_after
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::idempotence
