---
# Idempotence test tasks

- block:

  - block:

    - name: run idempotence test
      include_role:
        name: idempotence_tester
      vars:
        idempotence_tester_inventory: "{{ docker_sandbox_inventory }}"
        idempotence_tester_group: "{{ docker_sandbox_group }}"

    - name: setup fact to store idempotence test result
      set_fact:
        docker_sandbox_idempotence_result: >-
          {{ idempotence_tester_test_result }}

    when:
      - docker_sandbox_state in ["started", "recreated"]
      - docker_sandbox_idempotence_test
      - docker_sandbox_inventory | length > 0

  - name: recreate docker containers after running idempotence test
    include_tasks: provision.yml
    vars:
      docker_sandbox_images_override: []
      docker_sandbox_state_override: recreated
    when:
      - docker_sandbox_state in ["started", "recreated"]
      - docker_sandbox_idempotence_test
      - docker_sandbox_inventory | length > 0
      - docker_sandbox_idempotence_test_recreate_after

  tags:
    - role::docker_sandbox
    - role::docker_sandbox::idempotence
