---
# Sandbox inventory tasks

- block:
    - block:
        - name: Create temporary file for docker sandbox containers inventory
          tempfile:
            state: file
            suffix: .inventory.yml
          register: docker_sandbox_create_inventory_result

        - name: Setup fact with path to inventory
          set_fact:
            docker_sandbox_inventory: >-
              {{ docker_sandbox_create_inventory_result.path }}
      when:
        - docker_sandbox_state in ["started", "recreated"]
        - >-
          docker_sandbox_inventory is none
          or docker_sandbox_inventory | length == 0

    - name: Show inventory file path
      debug:
        msg: "{{ docker_sandbox_inventory }}"
      when: docker_sandbox_create_inventory_result is changed

    - name: Delete temporary file with docker sandbox containers inventory
      file:
        path: "{{ docker_sandbox_inventory }}"
        state: absent
      when: docker_sandbox_state == "absent"
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::inventory
