---
# Tasks to create docker testing containers inventory file

- block:

  - name: generate docker testing containers inventory file
    set_fact:
      docker_sandbox_inventory: >-
        {{ docker_sandbox_inventory_dir
          + "/"
          + "docker_sandbox_inventory_"
          + 9999999 | random | string
          + ".tmp" }}

  - name: create inventory file for docker testing containers
    template:
      src: inventory.j2
      dest: "{{ docker_sandbox_inventory }}"
      backup: no

  when: docker_sandbox_containers_state in ['present', 'started']
  tags:
    - role::docker_sandbox
