---
# Role tasks

- name: verify sandbox parameters
  include: verify.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::verify

- name: load sandbox presets
  include: presets.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::presets

- name: manage stalled containers
  include: stalled.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::stalled

- name: setup sandbox inventory
  include: inventory.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::inventory

- name: setup docker sandbox environment
  include: provision.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::provision

- name: run idempotence test
  include: idempotence.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::idempotence
