---
# Role tasks

- name: Run role dependencies
  import_tasks: dependencies.yml
  tags:
    - always

- name: Load sandbox presets
  import_tasks: presets.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::presets

- name: Get parent process id
  import_tasks: ppid.yml
  tags:
    - role::docker_sandbox

- name: Manage stalled containers
  import_tasks: stalled.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::stalled

- name: Setup sandbox inventory
  import_tasks: inventory.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::inventory

- name: Setup docker sandbox environment
  import_tasks: provision.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::provision

- name: Run idempotence test
  import_tasks: idempotence.yml
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::idempotence
