---
# Docker provision tasks

- name: provisione docker sandbox environment
  include_role:
    name: amtega.docker_provisioner
  vars:
    docker_provisioner_images: >-
      {{ (docker_sandbox_state in ["absent", "recreated"])
         | ternary([], docker_sandbox_images) }}
    docker_provisioner_image_state: present
    docker_provisioner_containers: "{{ docker_sandbox_containers }}"
    docker_provisioner_container_labels:
      docker_sandbox_ppid: >-
        {{ docker_sandbox_get_ppid_result.stdout }}
      docker_sandbox_user: "{{ ansible_facts.user_id }}"
      docker_sandbox_playbook: "{{ docker_sandbox_playbook }}"
      docker_sandbox_inventory: "{{ docker_sandbox_inventory }}"
    docker_provisioner_container_groups: ["{{ docker_sandbox_group }}"]
    docker_provisioner_container_tty: false
    docker_provisioner_inventory: >-
     {{ (docker_sandbox_state in ["started", "recreated"])
         | ternary(docker_sandbox_inventory, "") }}
    docker_provisioner_container_state: >-
       {{ (docker_sandbox_state in ["recreated"])
          | ternary("started", docker_sandbox_state) }}
    docker_provisioner_container_restart: true
    docker_provisioner_container_recreate: false
    docker_provisioner_force_kill: false
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::provision
