---
# Docker provision tasks

- name: provisione docker sandbox environment
  include_role:
    name: amtega.docker_provisioner
  vars:
    docker_sandbox_final_images: >-
      {{ docker_sandbox_images_override | default(docker_sandbox_images) }}
    container_state: >-
      {{ docker_sandbox_state_override | default(docker_sandbox_state) }}
    docker_provisioner_images: >-
      {{ (container_state in ["recreated", "absent"])
         | ternary([], docker_sandbox_final_images) }}
    docker_provisioner_image_state: present
    docker_provisioner_image_force: true
    docker_provisioner_containers: "{{ docker_sandbox_containers }}"
    docker_provisioner_container_labels:
      docker_sandbox_ppid: >-
        {{ lookup('pipe', 'ps -o ppid= -p `ps -o ppid= -p $PPID`') | trim }}
      docker_sandbox_user: >-
        {{ lookup('pipe', 'echo $USER') | trim }}
      docker_sandbox_playbook: "{{ docker_sandbox_playbook }}"
      docker_sandbox_inventory: "{{ docker_sandbox_inventory }}"
    docker_provisioner_container_groups: ["{{ docker_sandbox_group }}"]
    docker_provisioner_container_tty: false
    docker_provisioner_inventory: >-
      {{ (container_state in ["started", "recreated"])
         | ternary(docker_sandbox_inventory, "") }}
    docker_provisioner_container_state: >-
      {{ (container_state in ["recreated"])
         | ternary("started", docker_sandbox_state) }}
    docker_provisioner_container_restart: true
    docker_provisioner_container_recreate: >-
      {{ (container_state in ["recreated"]) | ternary(true, false) }}
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::provision
