---
# Stalled containers managament tasks

- block:
    - name: Get playbook file
      docker_sandbox_playbook:
      register: docker_sandbox_get_playbook_result

    - name: Setup fact with full playbook path
      set_fact:
        docker_sandbox_playbook: >-
          {{ playbook_dir }}/{{ docker_sandbox_get_playbook_result.playbook }}

    - name: Search previous dockers containers created by same parent ppid
      command: >-
        docker ps -a --format='{''{.Names}''}'
        --filter
        label=docker_sandbox_ppid={{ docker_sandbox_get_ppid_result.stdout }}
      changed_when: false
      when: docker_sandbox_cleanup_by_ppid | bool
      register: docker_sandbox_containers_by_ppid_result
      check_mode: no

    - name: Search previous dockers containers created by same user
      command: >-
        docker ps -a --format='{''{.Names}''}'
        --filter label=docker_sandbox_user={{ user }}
      changed_when: false
      when: docker_sandbox_cleanup_by_user | bool
      register: docker_sandbox_containers_by_user_result
      check_mode: no
      vars:
        user: >-
          {{ (ansible_facts.env | default(ansible_facts.ansible_env))["USER"] }}

    - name: Search previous dockers containers created by same playbook
      command: >-
        docker ps -a --format='{''{.Names}''}'
        --filter label=docker_sandbox_playbook={{ docker_sandbox_playbook }}
      changed_when: false
      when: docker_sandbox_cleanup_by_playbook | bool
      register: docker_sandbox_containers_by_playbook_result
      check_mode: no

    - name: Search previous dockers containers created with same inventory
      command: >-
        docker ps -a --format='{''{.Names}''}'
        --filter label=docker_sandbox_inventory={{ docker_sandbox_inventory }}
      changed_when: false
      when: docker_sandbox_cleanup_by_inventory | bool
      register: docker_sandbox_containers_by_inventory_result
      check_mode: no

    - name: Setup fact with stalled containers
      set_fact:
        docker_provisioner_stalled_containers: >-
          {{ lookup('template', 'stalled_containers.j2') | from_yaml }}
      vars:
        stalled_containers: >-
          {{ docker_sandbox_containers_by_ppid_result.stdout_lines
             | default([])
             | union(
                 docker_sandbox_containers_by_user_result.stdout_lines
                 | default([]))
             | union(
                 docker_sandbox_containers_by_playbook_result.stdout_lines
                 | default([]))
             | union(
                 docker_sandbox_containers_by_inventory_result.stdout_lines
                 | default([]))
             | difference(
                 docker_sandbox_containers | map(attribute='name') | list)
             | unique }}

    - name: Destroy previous stalled docker containers
      include_role:
        name: amtega.docker_provisioner
      when: docker_provisioner_containers | length > 0
      vars:
        docker_provisioner_images: []
        docker_provisioner_containers: >-
          {{ docker_provisioner_stalled_containers }}
        docker_provisioner_in_memory_inventory: false
  tags:
    - role::docker_sandbox
    - role::docker_sandbox::stalled
