---
# Stalled containers managament tasks

- block:

  - name: get playbook file
    docker_sandbox_playbook:
    register: docker_sandbox_get_playbook_result

  - name: setup fact with full playbook path
    set_fact:
      docker_sandbox_playbook: >-
        {{ playbook_dir }}/{{ docker_sandbox_get_playbook_result.playbook }}

  - name: search previous dockers containers created by same parent ppid
    shell: >-
      docker ps -a --format='{''{.Names}''}'
      --filter label=docker_sandbox_ppid={{ lookup(
        'pipe',
        'ps -o ppid= -p `ps -o ppid= -p $PPID`')
        | trim }}
    changed_when: false
    when: docker_sandbox_cleanup_by_ppid
    register: docker_sandbox_containers_by_ppid_result
    check_mode: no

  - name: search previous dockers containers created by same user
    shell: >-
      docker ps -a --format='{''{.Names}''}'
      --filter label=docker_sandbox_user={{ lookup(
        'pipe',
        'echo $USER')
        | trim }}
    changed_when: false
    when: docker_sandbox_cleanup_by_user
    register: docker_sandbox_containers_by_user_result
    check_mode: no

  - name: search previous dockers containers created by same playbook
    shell: >-
      docker ps -a --format='{''{.Names}''}'
      --filter label=docker_sandbox_playbook={{ docker_sandbox_playbook }}
    changed_when: false
    when: docker_sandbox_cleanup_by_playbook
    register: docker_sandbox_containers_by_playbook_result
    check_mode: no

  - name: search previous dockers containers created with same inventory
    shell: >-
      docker ps -a --format='{''{.Names}''}'
      --filter label=docker_sandbox_inventory={{ docker_sandbox_inventory }}
    changed_when: false
    when: docker_sandbox_cleanup_by_inventory
    register: docker_sandbox_containers_by_inventory_result
    check_mode: no

  - name: cleanup previous docker containers
    docker_container:
      name: "{{ item }}"
      state: absent
      force_kill: true
    when: >-
      docker_sandbox_cleanup_by_ppid
      or docker_sandbox_cleanup_by_user
      or docker_sandbox_cleanup_by_playbook
      or docker_sandbox_cleanup_by_inventory
    with_items: >-
      {{ docker_sandbox_containers_by_ppid_result.stdout_lines | default([])
        | union(
            docker_sandbox_containers_by_user_result.stdout_lines
              | default([]))
        | union(
            docker_sandbox_containers_by_playbook_result.stdout_lines
              | default([]))
        | union(
            docker_sandbox_containers_by_inventory_result.stdout_lines
              | default([]))
        | difference(
            docker_sandbox_containers | map(attribute='name') | list)
        | unique }}

  tags:
    - role::docker_sandbox
    - role::docker_sandbox::stalled
