---
# Drop a sandbox environment

- name: cleanup docker docker sandbox
  hosts: localhost
  vars_prompt:
    - name: "docker_sandbox_inventory"
      prompt: >-
        Enter absolute path to docker sandbox inventory file
        (if not given will try to cleanup all docker sandboxes)
      private: no
  roles:
    - role: docker_sandbox
      docker_sandbox_state: absent
