---
# Create a sandbox environment

- name: Create docker sandbox environment
  hosts: localhost
  vars_prompt:
    - name: docker_sandbox_inventory
      prompt: >-
        Enter absolute path to docker sandbox inventory file
        (if not given a random one will be created)
      private: no
  roles:
    - role: amtega.docker_presets
      docker_presets_images_json_query: "[? name != '']"

    - role: amtega.docker_sandbox
      docker_sandbox_state: started
      docker_sandbox_idempotence_test: false
      docker_sandbox_cleanup_by_ppid: false
      docker_sandbox_cleanup_by_user: false
      docker_sandbox_cleanup_by_playbook: false
  tasks:
    - debug: var=docker_sandbox_inventory
